# Generated by Django 5.0.7 on 2024-07-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_tutorialcategory_tutorial_tutorial_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialcategory",
            name="category_image",
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AddField(
            model_name="tutorialseries",
            name="series_image",
            field=models.CharField(default=1, max_length=500),
        ),
    ]
